services:
  backend:
    build:
      context: ./backend
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - API_PORT=5000
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - PUBLIC_URL=.
      - BROWSER=none
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start -- --host 0.0.0.0 --port 3000
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge