version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: chatbot-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://<BACKEND_PUBLIC_URL>:5000  # replace with cloud/public URL
    depends_on:
      - backend
    restart: unless-stopped
