services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: chatbot-backend-prod
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=production
      - API_PORT=8000
      - CORS_ORIGINS=http://localhost
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: chatbot-frontend-prod
    env_file:
      - .env.prod
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - PUBLIC_URL=.
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod # optional if you have a custom Dockerfile for nginx
    container_name: chatbot-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./backend:/app/backend:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
