app = "my-chatbot-app"  # <- your Fly app name
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "./Dockerfile.fly"

[env]
  ENVIRONMENT = "production"
  API_PORT = "8000"
  REACT_APP_API_URL = "https://my-chatbot-app.fly.dev"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
