app = "PoliticalAIChatbot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
ENVIRONMENT = "production"
API_PORT = "8080"

[build]
  dockerfile = "Dockerfile.fly"
  context = "." 

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[deploy]
  release_command = ""

[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    hard_limit = 25
    soft_limit = 20
